### PR TITLE
Sudo all the default writes in security

### PR DESCRIPTION
**Pull request by nateberkopec**
This is the only way I could get it work in Monterey 🤷

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Hey @nateberkopec, hope you're well!

What's happening for you without these; do they just not take effect or do the commands fail?

**Comment by nateberkopec** [comment]
@MikeMcQuaid Yo! I get a `The domain/default pair FOO does not exist` message with non-zero exit. I didn't check to see if it actually wrote anything or not, I assumed it didn't.

**Comment by MikeMcQuaid** [comment]
@nateberkopec Weird, seems to be working fine here, perhaps because those values already exist and it's not a clean install?

**Comment by nateberkopec** [comment]
🤷‍♂️ Can only tell ya what I saw. Strap was the first thing I installed on my new MBP 14".

**Comment by kotleni** [comment]
🤨

**Comment by MikeMcQuaid** [comment]
@nateberkopec I'll play around a bit with this, want to be able to reproduce it in some form first.

@kotleni sup?

**Comment by MikeMcQuaid** [comment]
Bah, can't reproduce but merging as-is because it's basically harmless and I trust @nateberkopec.

**Comment by MikeMcQuaid** [comment]
Thanks for the PR @nateberkopec, you rock!

**Pull request merged**
