### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Take 2 on https://github.com/MikeMcQuaid/strap/pull/184.

### CODE REVIEW

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by MikeMcQuaid** [comment]
@kaylangan For some reason the script I'm running hangs until its killed by Azure for taking too long. This wasn't the case with Travis CI and I can't figure out why this is happening: https://dev.azure.com/MikeMcQuaid/MikeMcQuaid/_build/results?buildId=21&view=logs

**Comment by kaylangan** [comment]
Can you try [setting the timeout](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml#timeouts) to something higher than 60 minutes (the default)?

**Comment by ericsciple** [comment]
This sounds like an issue we recently fixed.

We have an issue when a descendant process is still running and holding onto the stream. The bash script task is hanging because the stream hasn't closed yet. We have a fix rolling out with the current deployment (will reach all accounts over the next couple weeks).

Try this workaround:
```bash
script/server 1>/dev/null 2>&1 &
```

**Comment by kaylangan** [comment]
@MikeMcQuaid just checked with the team and we have a fix rolling out now so it should hit your account any moment.

**Comment by MikeMcQuaid** [comment]
@ericsciple Perfect, that worked. Thanks for the assist ❤️

**Pull request merged**
