### PR TITLE
Add a temporary NOPASSWD to sudoers.d to reduce friction of strap

### PR DESCRIPTION
**Pull request by sihil**
As discussed in #123 the sudo session keep alive has been a bit poorly since Sierra. This is a potential alternative that seems to work well but does come with a potential security issue.

The basic strategy is to use the initial sudo permission to immediately add a temporary `NOPASSWD` entry to the users `sudoers.d`. This ensures that the password is not prompted for again. Obviously we must then remove this which is done by `rm -f` the file containing the entry in `cleanup()`.

This works well and doesn't require background tasks or anything. However, it does open a couple of _potential_ security issues:
 - during the strap script run, any process can access sudo without a password
 - if the strap script to fail to run `cleanup()` for whatever reason we leave the system in a state where sudo is available trivially

It might be possible to lock this down further (sudo has a fairly rich set of criteria) but I've not spent enough time with the sudoers man page to determine this yet. If you're open to an approach like this in principal I can continue to investigate.

### CODE REVIEW

**Comment by sihil** [comment]
I'm afraid I've broken the CI pipeline. Not exactly sure how it worked before but I suspect I don't know enough about the pipeline environment (I guess sudo is already password-less on the machines in question?).

Anyway - the key thing is a discussion around the approach which can happen without a working CI for now.

**Comment by MikeMcQuaid** [comment]
Nice idea!

> * during the strap script run, any process can access sudo without a password

I'm a 👎 on this for now until that's addressed. I think we'd need to limit this to only the stuff we care about being `sudo`d. Given this is relatively arbitrary given `brew cask` this may be tricky to accomplish. Perhaps `SUDO_ASKPASS` (a `brew cask` configuration variable) could be useful here.

> Not exactly sure how it worked before but I suspect I don't know enough about the pipeline environment (I guess sudo is already password-less on the machines in question?).

Yes, I think that's the case.

Thanks for the PR; I definitely like the idea of improving this so it works again.

**Comment by sihil** [comment]
To clarify, I mean processes owned by the user running strap - but that's still much broader than the current scenario of it being a single TTY. In fact, I now recall that the reason I eventually adopted this approach was _because_ it was available for any of the user's processes. This meant that cask installations that were previously failing (as they did't match the sudo timestamp TTY) worked correctly.

I like the idea of looking at `SUDO_ASKPASS`. The password could be stored in an env var and responded as desired. However I don't immediately see how to lock that down only to the desired processes - anything could feasibly inspect `SUDO_ASKPASS` of a running process and duplicate or execute it to exfiltrate the password.

Ultimately we need something that can give it out only to descendants of strap's bash shell (but regardless of the TTY a descendant is attached to). That won't be easy to pull off securely.

I understand your position though and will continue to ponder if there is a way of merging this upstream.

**Comment by MikeMcQuaid** [comment]
> To clarify, I mean processes owned by the user running strap - but that's still much broader than the current scenario of it being a single TTY.

Yup 👍. Generally macOS user machines are single-user which pretty much means "all user processes" at that point. That said, though, the previous approach also pretty much meant any `sudo` would work without password so I'm now less sure this is a downgrade (although the implementation still strikes me as a little hacky).

> However I don't immediately see how to lock that down only to the desired processes - anything could feasibly inspect `SUDO_ASKPASS` of a running process and duplicate or execute it to exfiltrate the password.

Yeh, an attack is still possible in this case but it just becomes a lot more involved. My £0.02 is that this is an acceptable level of risk to do by default and is more secure than what was there before.

**Comment by sihil** [comment]
> Yup 👍. Generally macOS user machines are single-user which pretty much means "all user processes" at that point. That said, though, the previous approach also pretty much meant any `sudo` would work without password so I'm now less sure this is a downgrade (although the implementation still strikes me as a little hacky).

Not sure that's true. If the user or another process tried to do sudo in a different TTY then they would be prompted for the password again. I don't deny that the implementation is a hack - was just trying to get something that worked.

> Yeh, an attack is still possible in this case but it just becomes a lot more involved. My £0.02 is that this is an acceptable level of risk to do by default and is more secure than what was there before.

OK - I'll have a look at this and see if I can get something working.

**Comment by MikeMcQuaid** [comment]
> Not sure that's true. If the user or another process tried to do sudo in a different TTY then they would be prompted for the password again. I don't deny that the implementation is a hack - was just trying to get something that worked.

Yes, you're right, thanks for the clarification 👍

**Comment by sihil** [comment]
Closing for now in favour of pursuing a `SUDO_ASKPASS` approach (see #219)

**Pull request closed without merging**
