### PR TITLE
Fix auth for OmniAuth 2.0

### PR DESCRIPTION
**Pull request by indirect**
The omniauth gem was upgraded to 2.0 despite a breaking change: GET
/github/auth no longer works. That means that the currently-deployed
macos-strap.herokuapp.com doesn't work, either.

The fix is to switch to POST /github/auth, which this changeset does. In
order to only ever POST for auth, the flow had to change a little bit:

1. Download button submits a form to POST for auth
2. Auth callback redirects to GET strap.sh

It was previously reversed, where the button went to strap.sh, and a GET
redirect was issued if there was no auth.

### CODE REVIEW

**Comment by indirect** [comment]
This may or may not be the exact flow that you want: it sends strap.sh directly from the auth callback, and leaves the user semi-hanging with a tab that says "redirecting you back to the app" that you have to close. If there's something else specific that would be better, I'm happy to change it.

**Comment by MikeMcQuaid** [comment]
Thanks for the PR @indirect! Want to try this out locally to think about the flow but I'm gonna revert Omniauth 2 for now in https://github.com/MikeMcQuaid/strap/pull/397

**Comment by indirect** [comment]
Sounds like a plan! If you want to try it out quickly, I spun up a copy of this PR live at https://indirect-strap.herokuapp.com. It turns out if you're already authed to GitHub it just downloads strap.sh like always.

**Comment by MikeMcQuaid** [comment]
Thanks so much for this @indirect 🎉 ❤️

**Comment by MikeMcQuaid** [comment]
(I slightly tweaked the behaviour/flow, hope you still like it)

**Comment by indirect** [comment]
Looks great!

**Pull request merged**
