### PR TITLE
Support Mac OS Mojave

### PR DESCRIPTION
**Pull request by dachew**

### CODE REVIEW

**Comment by braidn** [comment]
Does this closing mean that the current master already supports Mojave?

**Comment by dachew** [comment]
Nope, I don't see support for Mojave in the version check.  It's just `|14` that needs to be added.  Now, whether or not it's worth it to upgrade to Mojave yet, I can't comment on.

**Comment by MikeMcQuaid** [comment]
> Does this closing mean that the current master already supports Mojave?

Yes (https://github.com/MikeMcQuaid/strap/pull/175) and that this PR has loads of stuff unrelated to 10.14 support and doesn't explain any of it.

**Comment by dachew** [comment]
The pr is related to our fork and is a complete accident. It was supposed to be created against that fork, where the only difference is two lines where we added 10.14. If I could expunge all record of it, I would.

**Pull request closed without merging**
