### PR TITLE
readme: fix typo

### PR DESCRIPTION
**Pull request by LinusU**

### CODE REVIEW

**Comment by LinusU** [comment]
No good? In the script it's specified as

> logn "Forwarding local port 80 to 8080:"

**Comment by mikemcquaid** [comment]
Sorry, I have been messing around with this repo as it's not ready for prime-time yet. Your change is correct.

**Comment by LinusU** [comment]
No problem :)

**Comment by mikemcquaid** [comment]
Merged manually in 0c7dbae, thanks.

**Pull request closed without merging**
