### PR TITLE
strap.sh: pass Brewfile over STDIN

### PR DESCRIPTION
**Pull request by mikemcquaid**
Don't need an extra file for this.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
I think it's because my testing wasn't on a terminal. I'm going to revert this.

**Comment by blackjid** [comment]
why not just remove the `cat |` instead of a complete revert??

**Comment by mikemcquaid** [comment]
@blackjid Good idea, want to submit a pull request (as it was your idea)? If you'd rather not I'll probably just do that. I just wanted to do a quick revert rather than a longer fix as it was stylistic and I was low on time.

**Comment by blackjid** [comment]
done, https://github.com/mikemcquaid/strap/pull/48

**Pull request merged**
